### ISSUE TITLE
Question about the demo_loacl.py

### ISSUE THREAD

**Issue by Xuchen-Li** [Dongping-Chen/GUI-World#1]
Hello, thanks for your wonderful work.
I find that in demo_local.py
```
from models.videochat2_it import VideoChat2_it (line 15)
```
This line of code cannot be found in the references within the videochat2 repository.
Videochat2 now only provides videochat_vicuna, videochat_phi and videochat_mistral.

**Comment by Dongping-Chen** [comment]
Thanks for pointing out the mistake. Videochat2 has released a new version and changed the repository structure. I will soon upload the code and tutorials on how to run GUI-Vid.

**Comment by Xuchen-Li** [comment]
Thanks!
