### ISSUE TITLE
Missing keys in android subset data from huggingface datasets

### ISSUE THREAD

**Issue by pooruss** [Dongping-Chen/GUI-World#2]
Hi~ Thanks for the great work!

It seems that there are a few keys missing in the android subset data:
- system
- multi
- app
- region
- goal
- keyframes

I downloaded the data from here: https://huggingface.co/datasets/shuaishuaicdp/GUI-World/tree/main/Annotation/train

**Comment by Dongping-Chen** [comment]
Hi, thanks for reaching out. Given that the Android subset is derived directly from [RICO](http://www.interactionmining.org/rico.html), we only require human annotator to check the quality of the video, without using our annotation system to annotate the keyframes. That means the android subset indeed does not exist these keys.

**Comment by pooruss** [comment]
Thanks
