### ISSUE TITLE
Missing tasks/train_xx.py

### ISSUE THREAD

**Issue by XpracticeYSKM** [Dongping-Chen/GUI-World#3]
Thanks for your awesome work!

I wonder where is the file `tasks/train_xx.py` in scripts.

And, if I need to obtain the correct frame in `keyframes` of GUI-World dataset, how should I set the parameters of video_reader so that the frame ID corresponds to the keyframe images in the video?

**Comment by Dongping-Chen** [comment]
Thank you for reaching out! I have fixed the bugs in the scripts and updated the README with the keyframe identifier methods. For the keyframes used for benchmarking, we extract them and treat them as groups of images for Image LLMs. For the keyframes used for training, the training scripts will uniformly sample frames from the video.
